### ISSUE TITLE
Ignore non SVG files (.DS_Store)

### ISSUE THREAD

**Issue by johanvoeten** [HaoyCn/iconfont-plugin-webpack#11]
macOS has the tendency to create an .DS_Store file if previews of SVG files have been viewed in a directory. 

If so the plugin tries to parse the .DS_Store file as if it where an SVG file.

You would see this error.

```
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char:
    at error (/Users/johanvoeten/dev/nhtv/web/themes/custom/breda_university/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/johanvoeten/dev/nhtv/web/themes/custom/breda_university/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/johanvoeten/dev/nhtv/web/themes/custom/breda_university/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/johanvoeten/dev/nhtv/web/themes/custom/breda_university/node_modules/sax/lib/sax.js:1006:11)
    at SAXStream.write (/Users/johanvoeten/dev/nhtv/web/themes/custom/breda_university/node_modules/sax/lib/sax.js:239:18)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

Remove the .DS_Store file will result in successful iconfont being generated.

**Comment by djsmit** [comment]
Experiencing the same issue.

**Comment by HaoyCn** [comment]
I'm sorry for this late reply. But I updated this package just now to resolve this issue. Let me know if anything else I can do for you. Thanks.

**Comment by djsmit** [comment]
Awesome! Thanks a lot.
